exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-300} ST=${ST:-60} && \
    swayidle -w \
        timeout $LT 'swaylock -f -c 000000' \
        timeout $((LT + ST)) 'swaymsg "output * dpms off"' \
                      resume 'swaymsg "output * dpms on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * dpms off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * dpms on"'  \
        before-sleep 'swaylock -f -c 000000' \
        lock 'swaylock -f -c 000000' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'

# To turn off monitors when swaylock is active
exec swayidle -w \
        timeout 10 'if pgrep -x swaylock; then swaymsg output "*" dpms off; fi' \
        resume 'swaymsg output "*" dpms on'
